#cron:
#  image: chenzhao/gmission
#  links:
#    - gmissionbyuwsgi:docker-gmission
#  volumes:
#    - ../:/GMission-Server
#  working_dir: /GMission-Server/services/cron_jobs
#  command: python task.py

gmissionbyuwsgi:
    # image: chenzhao/gmission
  image: freeznet/gmission
  links:
    - localmysql:docker-mysql
    - redis:docker-redis
    - assignmentalg:server-assign
  volumes:
    - ../:/GMission-Server
    - /etc/localtime:/etc/localtime:ro
      #- /home/bigstone/MATLAB2014/:/matlab-home
      #- /home/bigstone/workspace/matlab/geocrowdMatlab/:/Matlab-Scripts
  working_dir: /GMission-Server/hkust-gmission
  command: uwsgi --ini ../docker/gmission_by_uwsgi/uwsgi.ini
  ports:
    - "9091:9090"


# celery:
#   image: chenzhao/gmission
#   links:
#     - redis:docker-redis
#     - phppush:docker-php-push
#   volumes:
#     - ../:/GMission-Server
#   environment:
#     - C_FORCE_ROOT=true
#   working_dir: /GMission-Server/services
#   command: celery -A push_msg.task worker

asyncjobs:
  image: freeznet/gmission
  links:
    - redis:docker-redis
    - phppush:docker-php-push
  volumes:
    - ../:/GMission-Server
    - /etc/localtime:/etc/localtime:ro
  environment:
    - C_FORCE_ROOT=true
  working_dir: /GMission-Server/services
  command: celery -A async_jobs.tasks worker


localmysql:
  image: tutum/mysql:latest
  environment:
    MYSQL_USER: "csp_team"
    MYSQL_PASS: "csp2014hkust"
    ON_CREATE_DB: "gmission_hkust"
  ports:
    - "3308:3306"
  volumes:
    - /mysql/data/:/var/lib/mysql/
    - /etc/localtime:/etc/localtime:ro


redis: # some redis warnings ignored..
  image: redis
  ports:
    - "6380:6379"
  volumes:
    - /etc/localtime:/etc/localtime:ro


phppush:
  image: tutum/apache-php
  ports:
    - "9899:80"
  volumes:
    - ../PHP-push:/app
    - /etc/localtime:/etc/localtime:ro

assignmentalg:
  image: java:8-jre
  links:
    - localmysql:docker-mysql
  volumes:
    - ~/apache-tomcat-8.0.30:/tomcat
  environment:
    - CATALINA_HOME=/tomcat
    - PATH=/tomcat/bin:$PATH
  working_dir: /tomcat/bin
  command: sh catalina.sh run
  ports:
    - "8081:8080"

