#cron:
#  image: chenzhao/gmission
#  links:
#    - gmissionbyuwsgi:docker-gmission
#  volumes:
#    - ../:/GMission-Server
#  working_dir: /GMission-Server/services/cron_jobs
#  command: python task.py


gmissionbyuwsgi:
    # image: chenzhao/gmission
  image: freeznet/gmission
  links:
    - localmysql:docker-mysql
    - redis:docker-redis
  volumes:
    - ../:/GMission-Server
      #- /home/bigstone/MATLAB2014/:/matlab-home
      #- /home/bigstone/workspace/matlab/geocrowdMatlab/:/Matlab-Scripts
  working_dir: /GMission-Server/hkust-gmission
  command: uwsgi --ini ../docker/gmission_by_uwsgi/uwsgi.ini
  ports:
    - "9090:9090"


celery:
  image: chenzhao/gmission
  links:
    - redis:docker-redis
    - phppush:docker-php-push
  volumes:
    - ../:/GMission-Server
  environment:
    - C_FORCE_ROOT=true
  working_dir: /GMission-Server/services
  command: celery -A push_msg.task worker


localmysql:
  image: tutum/mysql:latest
  environment:
    MYSQL_USER: "csp_team"
    MYSQL_PASS: "csp2014hkust"
    ON_CREATE_DB: "gmission_hkust"
  ports:
    - "3306:3306"
  volumes:
    - /mysql/data/:/var/lib/mysql/


redis: # some redis warnings ignored..
  image: redis


phppush:
  image: tutum/apache-php
  ports:
    - "9898:80"
  volumes:
    - ../PHP-push:/app
