gmissionbyuwsgi:
  build: ./gmission_by_uwsgi
  links:
    - mysql:docker-mysql
  volumes:
    - ../:/GMission-Server
  ports:
    - "9090:9090"

mysql:
  build: ./mysql
  ports:
    - "3306:3306"
  volumes_from:
    - mysqldata

mysqldata:
  build: ./mysql_data

