gmissionbyuwsgi:  # celery should be separated
  image: chenzhao/gmission
  links:
    - mysql:docker-mysql
    - redis:docker-redis
    - phppush:docker-php-push
  volumes:
    - ../:/GMission-Server
  command: /bin/sh /GMission-Server/docker/gmission_by_uwsgi/run.sh
  ports:
    - "9090:9090"

mysql:
  build: ./mysql
  ports:
    - "3306:3306"
  volumes_from:
    - mysqldata

mysqldata:
  image: tutum/mysql
  volumes:
    - /var/lib/mysql
  command: /bin/sh

redis: # some redis warnings ignored..
  image: dockerfile/redis

phppush:
  image: tutum/apache-php
  ports:
    - "9898:80"
  volumes:
    - ../PHP-push:/app



